# Generated by Django 3.2 on 2022-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rvrent', '0002_auto_20220523_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='rv',
            name='beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rv',
            name='maxPassangers',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='rv',
            name='modelYear',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='rv',
            name='otherInfo',
            field=models.TextField(default=''),
        ),
    ]
